Add Gender Class
AY2223S1-CS2103-F14-2/tp pull request #101
Opened 2022-10-06 12:47 UTC by deeyonn

Would like to merge this branch containing the added parameter "Gender" to the master branch.

Resolves #95 

Currently failing 3 tests:
1. parse_invalidValue_failure
2. parseCommand_edit
3. parse_multipleRepeatedFields_acceptsLast

Would appreciate any feedback regarding these tests.

2022-10-06 14:45 UTC, cliftonfelix requested changes
AddComandParserTest.java line 150 -> Add GENDER_DESC_BOB
EditCommandParserTest.java 
- line 185 -> remove whole line
- line 187 -> change to BOB

PersonUtil.java line 54 -> change to PREFIX_GENDER

2022-10-06 16:16 UTC, maryjess requested changes
Overall, looking good!
Just to make sure no files are left behind, here are the files that I changed, but I notice didn't change here:
- `test/java/seedu/address/model/person/PersonTest.java`
- `test/java/seedu/address/model/person/UniquePersonListTest.java`
- `test/java/seedu/address/model/person/AddressBookTest.java`

2022-10-07 05:59 UTC, cliftonfelix requested changes
- Add tests in `test/java/seedu/address/logic/parser/ParserUtilTest.java`
- `PersonTest.java` line 37 to add gender

2022-10-07 07:02 UTC, cliftonfelix approved these changes

2022-10-07 07:03 UTC, cliftonfelix approved these changes
LGTM!

2022-10-07 17:09 UTC, cliftonfelix requested changes

2022-10-07 17:09 UTC, cliftonfelix commented on src/main/java/seedu/address/model/person/Gender.java
> +        "Gender should only be one word containing alphabetical characters and it should not be blank";
Please change the message constraints according to REGEX validation

2022-10-08 04:08 UTC, maryjess approved these changes
LGTM, would be good if you can apply the changes to the comments even though it is just minor :)

2022-10-08 04:08 UTC, maryjess commented on src/test/java/seedu/address/model/person/GenderTest.java
> +        // invalid university name
Minor: Shouldn't the comment here be "invalid gender name"?

2022-10-08 04:08 UTC, maryjess commented on src/test/java/seedu/address/model/person/GenderTest.java
> +        // valid university name
Same here!

2022-10-08 18:47 UTC, cliftonfelix approved these changes

2022-10-08 18:47 UTC, merged