Add CAP class
AY2223S1-CS2103-F14-2/tp pull request #102
Opened 2022-10-06 14:12 UTC by maryjess

- Create Cap class
- Modify Person to support CAP field
- Update UI to reflect Cap field

Resolves #94.

2022-10-06 14:15 UTC, maryjess commented
Do you guys have any comments on whether I should capitalise the `"CAP"` in the UI and JSON file, or should I just keep it as `"Cap"`? Currently it is the latter in the JSON file, and the former in the UI.

2022-10-07 09:47 UTC, JasonCP14 requested changes
EditPersonDescriptorTest.java need to include CAP

2022-10-10 11:22 UTC, lulucopter approved these changes
Overall LGTM, good job

2022-10-10 11:27 UTC, lulucopter commented on src/test/java/seedu/address/model/person/CapTest.java
> +        assertFalse(Cap.isValidCap(-5.0, 5.0)); // negative cap value
Minor, but recommended to add in tests for alphabetical inputs and symbols eg. "asd" and "!@#"

2022-10-10 12:44 UTC, JasonCP14 approved these changes

2022-10-10 12:44 UTC, merged