Refine View Feature
AY2223S1-CS2103-F14-2/tp pull request #143
Opened 2022-10-20 11:10 UTC by maryjess

Changes made:
- Fix resolution error and text wrapping issue -- resolves #126 
- Change font size and thickness for CommandBox and ResultDisplay
- [Minor] Refine `INVALID_FORMAT_COMMAND_MESSAGE` by adding one new line
- Change `SUCCESS_MESSAGE` for `ViewCommand`: "Viewed Person"

2022-10-23 13:48 UTC, lulucopter approved these changes
LGTM

2022-10-23 18:47 UTC, cliftonfelix requested changes
It's nice that now our app is resizable and looks neat.

One small detail, please remove String.format in ViewCommandTest line 30 and 53.

2022-10-25 11:13 UTC, deeyonn approved these changes
LGTM

2022-10-25 17:49 UTC, cliftonfelix approved these changes

2022-10-25 17:51 UTC, merged